default:
	clang src/main.cpp src/services/lexAnalizeService.cpp src/services/tableCreateService.cpp src/models/token.cpp src/supportingFiles/lexicalBase.cpp -o lexicalAnalyzer.exe
	./lexicalAnalyzer.exe test.asm